In [14]:
import pandas as pd
import glob
import os

In [15]:
folder_path = r"../Datasets/solar irradiance datasets"

In [16]:
excel_files = glob.glob(os.path.join(folder_path, "*.xlsx"))

print("Total Files:", len(excel_files))

Total Files: 120

In [17]:
df_list = []

for file in excel_files:
    df = pd.read_excel(file)
    df_list.append(df)

merged_df = pd.concat(df_list, ignore_index=True)

print("Merged Successfully!")
print("Rows :", merged_df.shape[0])
print("Columns :", merged_df.shape[1])

Merged Successfully!
Rows : 4320
Columns : 5

In [18]:
merged_df.head()

        State      District    Year  Month  Insolation (in kWh/m²)
0  Tamil Nadu    Thiruvarur  2015.0  April                   169.0
1  Tamil Nadu     Sivaganga  2015.0  April                   167.0
2  Tamil Nadu   Thoothukudi  2015.0  April                   168.0
3  Tamil Nadu  Nagapattinam  2015.0  April                   172.0
4  Tamil Nadu    Dharmapuri  2015.0  April                   171.0

In [19]:
month_order = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

merged_df["Month"] = pd.Categorical(
    merged_df["Month"],
    categories=month_order,
    ordered=True
)

In [20]:
pivot_df = merged_df.pivot_table(
    index=["State", "District", "Year"],
    columns="Month",
    values="Insolation (in kWh/m²)"
).reset_index()

In [21]:
pivot_df["Year"].max()

2024.0

In [22]:
pivot_df["Year"] = pivot_df["Year"].astype(int)

In [23]:
pivot_df.tail()

Month,State,District,Year,January,February,March,April,May,June,July,August,September,October,November,December
315,Tamil Nadu,Virudhunagar,2020,156.0,166.0,195.0,165.0,153.0,157.0,136.0,169.0,146.0,156.0,106.0,121.0
316,Tamil Nadu,Virudhunagar,2021,136.0,157.0,195.0,156.0,121.0,142.0,113.0,100.0,142.0,101.0,74.0,150.0
317,Tamil Nadu,Virudhunagar,2022,157.0,150.0,195.0,154.0,135.0,141.0,111.0,128.0,161.0,111.0,109.0,121.0
318,Tamil Nadu,Virudhunagar,2023,149.0,153.0,181.0,153.0,142.0,146.0,123.0,177.0,118.0,137.0,103.0,127.0
319,Tamil Nadu,Virudhunagar,2024,141.0,178.0,188.0,162.0,120.0,131.0,112.0,147.0,148.0,106.0,88.0,97.0

In [24]:
pivot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      320 non-null    object
 1   District   320 non-null    object
 2   Year       320 non-null    int32
 3   January    320 non-null    float64
 4   February   320 non-null    float64
 5   March      320 non-null    float64
 6   April      320 non-null    float64
 7   May        320 non-null    float64
 8   June       320 non-null    float64
 9   July       320 non-null    float64
 10  August     320 non-null    float64
 11  September  320 non-null    float64
 12  October    320 non-null    float64
 13  November   320 non-null    float64
 14  December   320 non-null    float64
dtypes: float64(12), int32(1), object(2)
memory usage: 36.4+ KB

In [33]:
pivot_df["District"].nunique()

32

In [34]:
print(os.getcwd())

d:\Final Year Project 2027\Electricity Demand and Supply Forecasting\Python files

In [36]:
pivot_df.to_csv(
    r"d:\Final Year Project 2027\Electricity Demand and Supply Forecasting\Datasets\solar_irradiance.csv",
    index=False
)