# Rainfall Data's

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv("../Datasets/Rainfall datasets.csv")
df1["Date"].min()

'2015-01-01'

In [3]:
df1["Date"].max()

'2025-12-01'

# Temperature Data's

In [4]:
df1=pd.read_csv("../Datasets/Temperature Dataset.csv")
df1["Date"].min()

'2015-01-01'

In [5]:
df1["Date"].max()

'2025-12-01'

# Humidity Data's

In [6]:
df1=pd.read_csv("../Datasets/Humidity Datasets.csv")
df1["Date"].min()

'2015-01-01'

In [7]:
df1["Date"].max()

'2025-12-01'

# solar irradinace data's

In [8]:
df1=pd.read_csv("../Datasets/solar_irradiance.csv")
df1["Date"].min()

'2015-01-01'

In [9]:
df1["Date"].max()

'2024-12-01'

# Peak Demand Data's

In [10]:
df1=pd.read_csv("../Datasets/Peak_Demand.csv")
df1["Date"].min()

'2015-04-01'

In [11]:
df1["Date"].max()

'2026-05-01'

In [12]:
df=pd.read_excel("../Datasets/Supply dataset.xlsx")
df.head()

,Parameter,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,Coal - Generation (in MU),70195.44,75339.79,69044.77,70322.24,69569.23,75185.34,81921.11,71886.66,75932.58,...,120750.65,115835.15,111274.42,105966.91,103811.19,102453.72,99520.45,96167.54,96119.81,111373.68
1,Oil & Gas - Generation (in MU),3246.28,3242.43,3796.41,3662.57,3854.07,4372.24,4156.93,4038.93,4263.18,...,1785.82,3195.53,2782.33,2809.12,2545.81,2054.73,2440.19,1454.48,1700.54,1978.63
2,Nuclear - Generation (in MU),3506.10,3457.01,3449.28,3022.21,2834.19,2806.70,2876.22,2868.49,2950.27,...,4719.07,4951.45,5137.08,4498.01,4536.36,4105.67,4045.28,4808.57,3860.28,4221.94
3,Hydro - Generation (in MU),9421.19,12854.80,12509.46,15094.48,17779.11,12299.09,9025.41,6821.86,6339.87,...,8763.28,9618.15,13264.60,16775.50,21673.90,23515.94,22317.41,16437.39,9816.95,8767.19
4,Solar - Generation (in MU),512.31,560.91,515.11,455.52,510.73,600.51,726.49,578.11,651.61,...,16811.38,15811.82,14305.32,12927.48,12100.63,12634.93,13556.18,13063.15,13185.97,14946.83

In [13]:
df = df.set_index("Parameter").T.reset_index()
df = df.rename(columns={"index": "Date"})

In [14]:
df.head()

Parameter,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Growth Rate (in %)
0,2015-04,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,NaN
1,2015-05,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,NaN
2,2015-06,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,NaN
3,2015-07,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,NaN
4,2015-08,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,NaN

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
supply=pd.read_excel("../Datasets/Supply dataset.xlsx")
supply.head()

,Parameter,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,Coal - Generation (in MU),70195.44,75339.79,69044.77,70322.24,69569.23,75185.34,81921.11,71886.66,75932.58,...,120750.65,115835.15,111274.42,105966.91,103811.19,102453.72,99520.45,96167.54,96119.81,111373.68
1,Oil & Gas - Generation (in MU),3246.28,3242.43,3796.41,3662.57,3854.07,4372.24,4156.93,4038.93,4263.18,...,1785.82,3195.53,2782.33,2809.12,2545.81,2054.73,2440.19,1454.48,1700.54,1978.63
2,Nuclear - Generation (in MU),3506.10,3457.01,3449.28,3022.21,2834.19,2806.70,2876.22,2868.49,2950.27,...,4719.07,4951.45,5137.08,4498.01,4536.36,4105.67,4045.28,4808.57,3860.28,4221.94
3,Hydro - Generation (in MU),9421.19,12854.80,12509.46,15094.48,17779.11,12299.09,9025.41,6821.86,6339.87,...,8763.28,9618.15,13264.60,16775.50,21673.90,23515.94,22317.41,16437.39,9816.95,8767.19
4,Solar - Generation (in MU),512.31,560.91,515.11,455.52,510.73,600.51,726.49,578.11,651.61,...,16811.38,15811.82,14305.32,12927.48,12100.63,12634.93,13556.18,13063.15,13185.97,14946.83

In [17]:
supply = supply.set_index("Parameter")

# Transpose (rows ↔ columns)
supply = supply.T

# Convert index into a column
supply = supply.reset_index()

# Rename the first column
supply = supply.rename(columns={"index": "Date"})

# Remove the name of the columns index (optional but recommended)
supply.columns.name = None

# Convert Date column to datetime
supply["Date"] = pd.to_datetime(supply["Date"], format="%Y-%m")

# Display
supply.head()

,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Growth Rate (in %)
0,2015-04-01,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,NaN
1,2015-05-01,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,NaN
2,2015-06-01,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,NaN
3,2015-07-01,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,NaN
4,2015-08-01,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,NaN

In [18]:
cols=supply.columns
supply=supply.drop(columns=cols[-1])
supply.head()

,Date,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total
0,2015-04-01,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65
1,2015-05-01,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87
2,2015-06-01,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99
3,2015-07-01,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27
4,2015-08-01,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52

In [19]:
supply.to_csv("../Datasets_For_Model_Training/Supply dataset.csv",index=False)

In [20]:
import pandas as pd
import os
from functools import reduce

# Folder containing all datasets
folder_path = "../Datasets_For_Model_Training/"

# Read all CSV files
dfs = []

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder_path, file), parse_dates=["Date"])
        dfs.append(df)

# Merge all datasets on the Date column
merged_df = reduce(
    lambda left, right: pd.merge(left, right, on="Date", how="inner"),
    dfs
)

# Display
print(merged_df.head())
print("Shape:", merged_df.shape)

# Save the merged dataset
merged_df.to_csv("../Datasets/final_merged_dataset.csv", index=False)

print("Merged successfully!")

        Date  Humidity  Peak_Demand    Rainfall  Solar_Irradiance  \
0 2015-04-01     70.07        12969  130.566857            166.53
1 2015-05-01     77.22        13295  160.792286            155.03
2 2015-06-01     77.55        13278   98.240286            160.31
3 2015-07-01     73.18        14615   37.804286            166.41
4 2015-08-01     72.58        13757   63.944286            167.12

   Coal - Generation (in MU)  Oil & Gas - Generation (in MU)  \
0                   70195.44                         3246.28
1                   75339.79                         3242.43
2                   69044.77                         3796.41
3                   70322.24                         3662.57
4                   69569.23                         3854.07

   Nuclear - Generation (in MU)  Hydro - Generation (in MU)  \
0                       3506.10                     9421.19
1                       3457.01                    12854.80
2                       3449.28                    12509.46
3                       3022.21                    15094.48
4                       2834.19                    17779.11

   Solar - Generation (in MU)  Wind - Generation (in MU)  \
0                      512.31                    1832.30
1                      560.91                    2673.76
2                      515.11                    3946.56
3                      455.52                    6591.88
4                      510.73                    5113.45

   Small-Hydro - Generation (in MU)  Bio Power - Generation (in MU)  \
0                            519.15                         1688.88
1                            685.93                         1222.24
2                            775.37                          853.03
3                           1069.77                          742.60
4                           1166.68                          726.06

       Total  Temperature
0   90921.65        28.57
1  100036.87        27.95
2   94889.99        27.31
3  100961.27        27.68
4  101553.52        27.85
Shape: (117, 15)
Merged successfully!

In [21]:
final=pd.read_csv("../Datasets/final_merged_dataset.csv")
final.head()

,Date,Humidity,Peak_Demand,Rainfall,Solar_Irradiance,Coal - Generation (in MU),Oil & Gas - Generation (in MU),Nuclear - Generation (in MU),Hydro - Generation (in MU),Solar - Generation (in MU),Wind - Generation (in MU),Small-Hydro - Generation (in MU),Bio Power - Generation (in MU),Total,Temperature
0,2015-04-01,70.07,12969,130.566857,166.53,70195.44,3246.28,3506.10,9421.19,512.31,1832.30,519.15,1688.88,90921.65,28.57
1,2015-05-01,77.22,13295,160.792286,155.03,75339.79,3242.43,3457.01,12854.80,560.91,2673.76,685.93,1222.24,100036.87,27.95
2,2015-06-01,77.55,13278,98.240286,160.31,69044.77,3796.41,3449.28,12509.46,515.11,3946.56,775.37,853.03,94889.99,27.31
3,2015-07-01,73.18,14615,37.804286,166.41,70322.24,3662.57,3022.21,15094.48,455.52,6591.88,1069.77,742.60,100961.27,27.68
4,2015-08-01,72.58,13757,63.944286,167.12,69569.23,3854.07,2834.19,17779.11,510.73,5113.45,1166.68,726.06,101553.52,27.85

In [22]:
final.shape

(117, 15)