# importing necessary libraries to do the pre-processing

In [29]:
import numpy as np
import pandas as pd

# Loading the Dataset from the folder

In [30]:
df=pd.read_csv("../Datasets/solar_irradiance.csv")
df.head()

,State,District,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,Tamil Nadu,Ariyalur,2015,137.0,163.0,201.0,166.0,151.0,167.0,162.0,168.0,159.0,139.0,85.0,110.0
1,Tamil Nadu,Ariyalur,2016,160.0,174.0,206.0,192.0,164.0,150.0,147.0,175.0,151.0,160.0,135.0,147.0
2,Tamil Nadu,Ariyalur,2017,147.0,171.0,186.0,196.0,174.0,173.0,151.0,152.0,155.0,141.0,110.0,148.0
3,Tamil Nadu,Ariyalur,2018,159.0,163.0,187.0,170.0,162.0,164.0,138.0,164.0,162.0,127.0,121.0,147.0
4,Tamil Nadu,Ariyalur,2019,136.0,163.0,175.0,178.0,180.0,173.0,108.0,137.0,148.0,126.0,139.0,137.0

# Keeping only important columns

In [31]:
df=df.iloc[:,2:]
df.head()

,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,2015,137.0,163.0,201.0,166.0,151.0,167.0,162.0,168.0,159.0,139.0,85.0,110.0
1,2016,160.0,174.0,206.0,192.0,164.0,150.0,147.0,175.0,151.0,160.0,135.0,147.0
2,2017,147.0,171.0,186.0,196.0,174.0,173.0,151.0,152.0,155.0,141.0,110.0,148.0
3,2018,159.0,163.0,187.0,170.0,162.0,164.0,138.0,164.0,162.0,127.0,121.0,147.0
4,2019,136.0,163.0,175.0,178.0,180.0,173.0,108.0,137.0,148.0,126.0,139.0,137.0

# Extracting the columns from the datasets

In [32]:
months=df.columns
months

Index(['Year', 'January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='object')

# Doing the average for the 32 districts and making it for single year and round that value to 2 decimbal places

In [33]:
month_avg=df.groupby("Year")[months[1:]].mean().reset_index().round(2)
month_avg

,Year,January,February,March,April,May,June,July,August,September,October,November,December
0,2015,146.56,162.97,194.53,166.53,155.03,160.31,166.41,167.12,157.25,143.69,92.62,114.06
1,2016,162.75,174.41,204.47,191.19,166.19,147.03,149.69,177.66,167.12,166.78,135.03,142.28
2,2017,151.66,167.91,187.81,195.72,176.59,162.94,155.00,157.41,164.66,149.09,119.62,149.03
3,2018,162.38,164.25,186.84,182.44,163.84,155.94,140.81,169.44,173.75,137.09,124.50,140.66
4,2019,136.78,161.78,173.19,175.25,182.12,169.00,111.38,141.22,151.53,132.09,142.81,130.81
5,2020,158.50,169.00,198.09,171.81,168.47,155.97,140.03,161.88,145.47,158.00,112.75,128.50
6,2021,139.22,160.22,201.50,164.19,137.75,146.72,120.50,111.44,140.84,116.31,79.84,150.62
7,2022,157.91,157.19,186.81,167.75,141.69,151.25,116.22,134.19,150.75,113.00,109.66,123.69
8,2023,152.22,156.09,188.16,166.75,148.91,149.31,113.38,168.00,134.56,152.19,107.88,126.44
9,2024,140.88,180.50,192.62,179.38,126.38,134.44,109.97,147.25,156.84,120.78,101.47,98.66

# converting the rows into cols for better readability and model training too

In [36]:
final=month_avg.melt(
    id_vars="Year",
    var_name="Months",
    value_name="Solar_Irradiance"
)

In [37]:
final

     Year    Months  Solar_Irradiance
0    2015   January            146.56
1    2016   January            162.75
2    2017   January            151.66
3    2018   January            162.38
4    2019   January            136.78
..    ...       ...               ...
115  2020  December            128.50
116  2021  December            150.62
117  2022  December            123.69
118  2023  December            126.44
119  2024  December             98.66

[120 rows x 3 columns]

# Doing the Feature Engineering and making the Date column from the Year and Month

In [ ]:
final["Date"]=pd.to_datetime(
final["Year"].astype(str)+"-"+final["Months"],
format="%Y-%B"
)

In [43]:
final=final[["Date","Solar_Irradiance"]]
final=final.sort_values("Date")
final.head()

         Date  Solar_Irradiance
0  2015-01-01            146.56
10 2015-02-01            162.97
20 2015-03-01            194.53
30 2015-04-01            166.53
40 2015-05-01            155.03

In [ ]:
final.to_csv("../Datasets/solar_irradiance.csv",index=False)

# Checking the Strcuture of the dataset

In [ ]:
df1=pd.read_csv("../Datasets/solar_irradiance.csv")

         Date  Solar_Irradiance
0  2015-01-01            146.56
1  2015-02-01            162.97
2  2015-03-01            194.53
3  2015-04-01            166.53
4  2015-05-01            155.03